apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: ghcr.io/scalable-a-team/chat-service
          env:
            - name: API_PREFIX
              value: "/api"
            - name: DB_HOST
              value: mongos1
            - name: DB_PORT
              value: "27017"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=ChatService"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: gh-regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: chat-service
