apiVersion: v1
kind: Secret
metadata:
  name: user-jwt-secret
type: Opaque
stringData:
  kongCredType: jwt
  key: login-buyer-issuer
  algorithm: HS256
  secret: user-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: seller-jwt-secret
type: Opaque
stringData:
  kongCredType: jwt
  key: login-seller-issuer
  algorithm: HS256
  secret: seller-secret
