apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: jwtheader
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  strip_claims: "false"
  token_required: "false"
plugin: kong-jwt2header

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-jwt-public
config:
  anonymous: anon
  claims_to_verify: 
    - exp
plugin: jwt

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: auth-all-acl
config: 
  allow:
  - seller
  - buyer
plugin: acl

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: buyer-acl
config: 
  allow:
  - buyer
plugin: acl

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: seller-acl
config: 
  allow:
  - seller
plugin: acl