apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: buyer
  annotations:
    kubernetes.io/ingress.class: kong
username: buyer
credentials:
  - user-jwt-secret
  - buyer-acl

---


apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: seller
  annotations:
    kubernetes.io/ingress.class: kong
username: seller
credentials:
  - seller-jwt-secret
  - seller-acl

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anon
  annotations:
    kubernetes.io/ingress.class: kong
username: anon