apiVersion: v1
kind: Secret
metadata:
  name: user-kong-jwt-secret
type: Opaque
stringData:
  kongCredType: jwt
  key: user-issuer
  algorithm: HS256
  secret: USERJWTSECRETA0zxco1

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  annotations:
    kubernetes.io/ingress.class: kong
username: user
credentials:
  - user-kong-jwt-secret

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anon
  annotations:
    kubernetes.io/ingress.class: kong
username: anon