apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-saga
  labels:
    app: order-saga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-saga
  template:
    metadata:
      labels:
        app: order-saga
    spec:
      containers:
      - name: order-saga
        image: ghcr.io/scalable-a-team/order-service-saga
        args: [ "-A", "tasks", "worker", "--loglevel=info", "-Q", "order", "-c", "1"]
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672//"
          - name: DB_HOST
            value: order-db
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: user
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: userdbpassword
      imagePullSecrets:
      - name: gh-regcred
