kind: PersistentVolume
apiVersion: v1
metadata:
  name: order-db-pv-volume
  labels:
    type: local-2
    app: order-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data1"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: order-db-pv-claim
  labels:
    app: order-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-db-volume
          env:
            - name: POSTGRES_PASSWORD
              value: userdbpassword
            - name: POSTGRES_DB
              value: order
      volumes:
        - name: order-db-volume
          persistentVolumeClaim:
            claimName: order-db-pv-claim