apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/scalable-a-team/order-service
        ports:
          - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
          - name: DB_HOST
            value: order-db
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: user
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: userdbpassword
      imagePullSecrets:
        - name: gh-regcred
