apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: product-service
  type: LoadBalancer