apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ghcr.io/scalable-a-team/elastic-products
        ports:
          - containerPort: 5000
        env:
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-cred-secrets
                key: access_key
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-cred-secrets
                key: secret
          - name: S3_ENDPOINT_URL
            value: "https://tanpantz.com:9000"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-cred-secrets
                key: access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-cred-secrets
                key: secret
      imagePullSecrets:
        - name: gh-regcred
