apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ghcr.io/scalable-a-team/user-service
        ports:
          - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=UserService"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
          - name: JWT_CUSTOMER_SECRET_KEY
            value: user-secret
          - name: JWT_SELLER_SECRET_KEY
            value: seller-secret
          - name: JWT_BUYER_ISS
            value: login-buyer-issuer
          - name: JWT_SELLER_ISS
            value: login-seller-issuer
          - name: JWT_IDENTITY_KEY
            value: username
          - name: DB_HOST
            value: user-db
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: user
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: userdbpassword
      imagePullSecrets:
        - name: gh-regcred
