apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-saga
  labels:
    app: user-saga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-saga
  template:
    metadata:
      labels:
        app: user-saga
    spec:
      containers:
      - name: user-saga
        image: ghcr.io/scalable-a-team/user-service-saga
        args: [ "-A", "tasks", "worker", "--loglevel=info", "-Q", "user", "-c", "1"]
        env:
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://signoz-otel-collector.signoz.svc.cluster.local:4317"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=UserSagaWorker"
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672//"
          - name: DB_HOST
            value: user-citus-coordinator
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: citus-secrets
                key: password
      imagePullSecrets:
      - name: gh-regcred
